# action.yml
name: 'upload-actions'
description: 'upload actions'
inputs:
  st:
    description: 'st'
    required: true
  filePath:
    description: 'file path'
    required: true
outputs:
  resId:
    description: 'resId'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.st }}
    - ${{ inputs.filePath }}